### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by nicejs-is-cool** [PrismarineJS/prismarine-proxy#24]
Like for prismarine-proxy itself not the minecraft protocol

**Comment by u9g** [comment]
whats confusing? Or is there something specific that you would like documented better?

**Comment by nicejs-is-cool** [comment]
I can't find documentation for this project anywhere

**Comment by u9g** [comment]
> I can't find documentation for this project anywhere

https://github.com/PrismarineJS/prismarine-proxy#usage-1

Unless you are looking for something more specific?

**Comment by nicejs-is-cool** [comment]
Okay..?
