### ISSUE TITLE
mineflayer

### ISSUE THREAD

**Issue by ItsOnlyMyUsername** [PrismarineJS/prismarine-proxy#32]
is it possible to change createClient from minecraft-protocol to createBot from mineflayer?

**Comment by ItsOnlyMyUsername** [comment]
Okay, i figured out how to do this by looking at the mineflayer source code.

https://github.com/PrismarineJS/mineflayer/blob/9497b67d85082317bf7bf7a19427ed9371cb2f49/lib/loader.js#L94
https://github.com/PrismarineJS/mineflayer/blob/9497b67d85082317bf7bf7a19427ed9371cb2f49/lib/loader.js#L71

as a result:
`const bot =  mineflayer.createBot({
      client: toServer,
      ...this.options.clientOptions
})`

**Comment by SinanAkkoyun** [comment]
@ItsOnlyMyUsername I tried this on start:
```js
proxy.on('start', (toClient: ServerClient, toServer: Client) => {
  const bot =  mineflayer.createBot({ client: toServer, ...proxy.options.clientOptions })
  bot.on('respawn', () => {
    console.log('YAY')
  })
})
```
With limited success:
```
/home/sinan/mc/proxy/node_modules/mineflayer/lib/plugins/physics.js:355
    bot.entity.height = 1.8
                      ^

TypeError: Cannot set properties of undefined (setting 'height')
    at Client.<anonymous> (/home/sinan/mc/proxy/node_modules/mineflayer/lib/plugins/physics.js:355:23)
```
